export const CREATE_LISTING = "CREATE_LISTING";
export const UPDATE_LISTING = "UPDATE_LISTING";
export const DELETE_LISTING = "DELETE_LISTING";
// export const DELETE_IMAGE = "DELETE_IMAGE";
export const FETCH_LISTING = "FETCH_LISTING";
// export const TEMP_LISTING_PHOTOS = "TEMP_LISTING_PHOTOS";
export const RESET_LISTING = "RESET_LISTING";
